### ISSUE TITLE
存放大型文件一种可能的解决方案

### ISSUE THREAD

**Issue by xqm32** [lib-hfut/lib-hfut#12]
可以存放到超星网盘（每个人有 100GB 的免费空间，且不限制上下行速度），并在资源中贴链接。

**Comment by DolorHunter** [comment]
主要是因爲現在還沒有什麽大文件需求，基本是文稿和代碼，所以也不太需要存放大文件，而且如果加入三方存儲的話維護起來會比較困難，而且數據如果由每一個上傳者保存容易失效，集中保存又需要專人管理，而且三方平臺也有三方的問題。我覺得倒是可以用雲盤加一個 zip 包功能，把課程的所有内容下載了，把課程的 zip 包可以放到雲盤，下載多文件應該比較方便。雲盤我覺得可以試下 OneDrive，貴校給每個人都開了永久 1T 空間，畢業也可以一直用，算是可以薅一下的小福利。感謝提議。
